version: '3.4'

services:
  dipterv.server:
    image: ${DOCKER_REGISTRY-}diptervserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
     - sqlserver

  zookeeper:
    hostname: zookeeper
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    hostname: kafka
    image: debezium/kafka:latest
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  sqlserver:
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 3033:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - MSSQL_SA_PASSWORD=Password123!
     - MSSQL_AGENT_ENABLED=true
    volumes:
      - sqlData:/var/opt/mssql

  connect:
    hostname: connect
    image: debezium/connect:latest
    ports:
     - 8083:8083
    links:
     - kafka
     - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

volumes:
  sqlData:
    external: false
