version: '3.7'

services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    hostname: kafka
    container_name: kafka
    image: debezium/kafka:latest
    ports:
     - "29092:29092"
     - "9092:9092"
     - "9101:9101"
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     - KAFKA_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    links:
     - zookeeper
     - kafka
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  sqlserver:
    hostname: sqlserver
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 3033:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - MSSQL_SA_PASSWORD=Password123!
     - MSSQL_AGENT_ENABLED=true
    volumes:
      - sqlData:/var/opt/mssql

  connect:
    hostname: connect
    container_name: connect
    image: debezium/connect:latest
    ports:
     - 8083:8083
    links:
     - kafka
     - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

volumes:
  sqlData:
    external: false